# Copyright 2026 Aayush Chawla
# SPDX-License-Identifier: Apache-2.0

"""Centralized search limit constants for chat tools and coherence pipeline."""

# Chat tool limits (per-call max and default)
CHAT_SEARCH_MAX = 200
CHAT_SEARCH_DEFAULT = 20

SEMANTIC_SEARCH_MAX = 200
SEMANTIC_SEARCH_DEFAULT = 10

ENTITY_SEARCH_MAX = 200
ENTITY_SEARCH_DEFAULT = 10

CARDS_BY_ENTITY_MAX = 200
CARDS_BY_ENTITY_DEFAULT = 25

RECENT_ACTIVITY_MAX = 200
RECENT_ACTIVITY_DEFAULT = 10

CONTACT_SEARCH_MAX = 20

# Coherence / trace pipeline
TRACE_TEXT_SEARCH_MAX = 200
TRACE_IDENTIFIER_SEARCH_MAX = 30
TRACE_SEMANTIC_SEARCH_MAX = 30
TRACE_ENTITY_SEARCH_MAX = 20
TRACE_FUZZY_SEARCH_MAX = 30
TRACE_EVENT_SEARCH_MAX = 20
